-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session",
        -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on",
        -- to avoid having to press a key twice to turn on the display.
    },
})

hl.config({
    listener = {
        timeout = 600,
        -- 10 min
        on_timeout = "loginctl lock-session",
        -- lock screen when timeout has passed
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        timeout = 420,
        -- 12 min
        on_timeout = "hyprctl dispatch dpms off",
        -- screen off when timeout has passed
        on_resume = "hyprctl dispatch dpms on && brightnessctl -r",
        -- screen on when activity is detected after timeout has fired.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

--listener {

--    timeout = 1800                                # 30min

--    on-timeout = systemctl suspend                # suspend pc

--}
