-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "/home/tyler/Wallpapers/0-ship-at-sea.jpg"

-- TODO: manual review: wallpaper = "HDMI-A-2", "/home/tyler/Wallpapers/0-ship-at-sea.jpg"

-- TODO: manual review: wallpaper = "DP-3", "/home/tyler/Wallpapers/0-ship-at-sea.jpg"
