-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- BACKGROUND

hl.config({
    background = {
        path = "~/.config/custom/current/background",
        blur_passes = 2,
        contrast = 0.8916,
        brightness = 0.8172,
        vibrancy = 0.1696,
        vibrancy_darkness = 0.0,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

-- GENERAL

hl.config({
    general = {
        no_fade_in = false,
        grace = 0,
        screencopy_mode = 1,
        disable_loading_bar = false,
    },
})

-- INPUT FIELD

hl.config({
    input-field = {
        size = { 250, 60 },
        outline_thickness = 2,
        dots_size = 0.2,
        -- Scale of input-field height, 0.2 - 0.8
        dots_spacing = 0.2,
        -- Scale of dots' absolute size, 0.0 - 1.0
        dots_center = true,
        outer_color = { "rgba(0", 0, 0, "0)" },
        inner_color = { "rgba(100", 114, 125, "0.4)" },
        font_color = { "rgb(200", 200, "200)" },
        fade_on_empty = false,
        font_family = "SF Pro Display Bold",
        placeholder_text = "<i><span foreground=##ffffff99 >Enter Pass</span></i>",
        hide_input = false,
        position = { 0, -225 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output

-- Time

hl.config({
    label = {
        text = "cmd[update:1000] echo <span>$(date + %I:%M )</span>",
        color = { "rgba(216", 222, 233, "0.70)" },
        font_size = 100,
        font_family = "SF Pro Display Bold",
        position = { 0, 240 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Day-Month-Date

hl.config({
    label = {
        text = { "cmd[update:1000] echo -e $(date + %A", "%d %B )" },
        color = { "rgba(216", 222, 233, "0.70)" },
        font_size = 30,
        font_family = "SF Pro Display Bold",
        position = { 0, 105 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- Profie-Photo

hl.config({
    image = {
        path = "/home/tyler/.config/hypr/tyler.png",
        border_color = "0xffdddddd",
        border_size = 0,
        size = 125,
        rounding = -1,
        rotate = 0,
        reload_time = -1,
        position = { 0, -20 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'image' may be a plugin or custom section; verify the output

-- USER

hl.config({
    label = {
        text = "Welcome Tyler",
        color = { "rgba(216", 222, 233, "0.70)" },
        font_size = 25,
        font_family = "SF Pro Display Bold",
        position = { 0, -130 },
        halign = "center",
        valign = "center",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

-- CURRENT SONG

hl.config({
    label = {
        text = "cmd[update:1000] echo $(~/.config/hypr/Scripts/songdetail.sh)",
        color = { "rgba(255", 255, 255, "0.7)" },
        font_size = 18,
        font_family = { "JetBrains Mono Nerd", "SF Pro Display Bold" },
        position = { 0, 60 },
        halign = "center",
        valign = "bottom",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output
