-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 2,
		border_size = 2,
		-- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = "rgb(8A8A8D)",
			inactive_border = "rgba(595959aa)",
		},
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 1,
		rounding_power = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hypr.land/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
		-- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
		--        NAME,           X0,   Y0,   X1,   Y1
		-- Default animations, see https://wiki.hypr.land/Configuring/Animations/
		--           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
		-- custom slide-in for swaync
	},
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

hl.workspace_rule({
	workspace = "w[tv1]",
	gaps_out = 0,
	gaps_in = 0,
})

hl.workspace_rule({
	workspace = "f[1]",
	gaps_out = 0,
	gaps_in = 0,
})

hl.window_rule({
	name = "no-gaps-wtv1",
	match = {
		float = false,
		workspace = "w[tv1]",
	},
	border_size = 0,
	rounding = 0,
})

hl.window_rule({
	name = "no-gaps-f1",
	match = {
		float = false,
		workspace = "f[1]",
	},
	border_size = 0,
	rounding = 0,
})

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

--dwindle {

--    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below

--    preserve_split = true # You probably want this

--}

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 0,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

-- Float anything with the tag "floatingWindow" (or "floatingWindow*")

hl.window_rule({
	name = "match_tag_floatingwi",
	match = {
		class = "float on",
	},
	-- TODO: review rule: "match:tag floatingWindow"
})

-- optional default size:

hl.window_rule({
	name = "match_tag_floatingwi",
	match = {
		class = "size 1000 700",
	},
	-- TODO: review rule: "match:tag floatingWindow"
})

hl.window_rule({
	name = "match_class___io__mi",
	match = {
		class = "tag +floatingWindow",
	},
	-- TODO: review rule: "match:class ^(io\\.missioncenter\\.MissionCenter)$"
})

-- All scratch TUIs (Ghostty windows launched with this class)

hl.window_rule({
	name = "match_class___com__t",
	match = {
		class = "float on",
	},
	-- TODO: review rule: "match:class ^(com\\.tmchase\\.scratchtui)$"
})

hl.window_rule({
	name = "match_class___com__t",
	match = {
		class = "center on",
	},
	-- TODO: review rule: "match:class ^(com\\.tmchase\\.scratchtui)$"
})

hl.window_rule({
	name = "match_class___com__t",
	match = {
		class = "size 900 600",
	},
	-- TODO: review rule: "match:class ^(com\\.tmchase\\.scratchtui)$"
})
