-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--#############1#

--## MONITORS #11

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.env("GDK_SCALE", 1)

hl.monitor({
    output   = "DP-3",
    mode     = "1920x1080@120",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x1080@60",
    position = "-1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "",
    mode     = "prefered",
    position = "auto",
    scale    = 1,
})

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = 6,
    monitor = "HDMI-A-2",
})

hl.workspace_rule({
    workspace = 7,
    monitor = "HDMI-A-2",
})

hl.workspace_rule({
    workspace = 8,
    monitor = "HDMI-A-2",
})

hl.workspace_rule({
    workspace = 9,
    monitor = "HDMI-A-2",
})
